### ISSUE TITLE
Exception running denorm_daemon in python 3.7

### ISSUE THREAD

**Issue by hacker-cb** [django-denorm/django-denorm#90]
I got `AttributeError: module 'os' has no attribute 'errno'` error running denorm_daemon in python 3.7.6.

Generally problem is that in python 3.7 os.errno is no longer available.

Full trace:
```
$ ./manage.py denorm_daemon
Traceback (most recent call last):
  File "/Users/pavel/projects/tvip_erp/.env/lib/python3.7/site-packages/denorm/management/commands/denorm_daemon.py", line 59, in pid_exists
    pid = int(open(pidfile, 'r').read())
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/django-denorm-daemon-pid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 21, in <module>
    main()
  File "./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/pavel/projects/tvip_erp/.env/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/pavel/projects/tvip_erp/.env/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/pavel/projects/tvip_erp/.env/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/pavel/projects/tvip_erp/.env/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/Users/pavel/projects/tvip_erp/.env/lib/python3.7/site-packages/denorm/management/commands/denorm_daemon.py", line 17, in _commit_manually
    res = fn(*args, **kwargs)
  File "/Users/pavel/projects/tvip_erp/.env/lib/python3.7/site-packages/denorm/management/commands/denorm_daemon.py", line 78, in handle
    if self.pid_exists(pidfile):
  File "/Users/pavel/projects/tvip_erp/.env/lib/python3.7/site-packages/denorm/management/commands/denorm_daemon.py", line 64, in pid_exists
    return err.errno == os.errno.EPERM
AttributeError: module 'os' has no attribute 'errno'
```

**Comment by mpasternak** [comment]
Fork with Python 3.8 support, http://github.com/mpasternak/django-denorm-iplweb, no PyPI releases yet. Feel free to submit patches. This problem is fixed there already.
